name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    env:
      IMGUI_VERSION: 18311_docking

    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: Windows MSVC

    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.6'
          architecture: 'x64'

      - name: Install conan
        run: |
          pip install wheel setuptools
          pip install conan

      - name: Create imgui conan package
        run: conan create . imgui/${{ env.IMGUI_VERSION }}@

      - name: Go to .conan/data dir
        shell: pwsh
        run: |
          $env:CONAN_HOME_DIR=$(conan config home)
          $env:CONAN_HOME_DIR
          echo "CONAN_HOME_DIR=$($env:CONAN_HOME_DIR)" >> $GITHUB_ENV
          cd $env:CONAN_HOME_DIR/data
          Get-Location
          dir imgui

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: imgui_${{ env.IMGUI_VERSION }}
          #${{ env.CONAN_HOME_DIR }}/data/imgui/**
          path: |
            C:\Users\runneradmin\.conan\data\imgui
            !C:\Users\runneradmin\.conan\data\imgui\${{ env.IMGUI_VERSION }}\_\_\build
            !C:\Users\runneradmin\.conan\data\imgui\${{ env.IMGUI_VERSION }}\_\_\export_source
            !C:\Users\runneradmin\.conan\data\imgui\${{ env.IMGUI_VERSION }}\_\_\source
